### ISSUE TITLE
Pyclui unavailable on armv7

### ISSUE THREAD

**Issue by hippiiee** [fO-000/bluescan#27]
Hello,
One of the dependencies : pyclui is not available on armv7 architecture,

```bash
sudo bluescan -h
Could not find "/usr/local/lib/python3.9/dist-packages/pyclui/pytransform/platforms/linux/armv7/_pytransform.so"
```

I think you are also the owner of that lib, could you open-source it so I can add the architecture compatibility ? Or could you add it ?

Thanks !

**Comment by fO-000** [comment]
Ah, this problem is not easy to solve at the moment. Let me explain:

1. bluescan currently only runs on **x64** and **arm64** machines.
2. Just making pyclui open source does not make bluescan run on armv7 machines. Because bluescan also involves many private libraries, such as commercial ones.
3. pylcui and other non-open source libraries are not just my own projects.
4. pyclui will be deprecated in the near future.

> ps: As far as I feel, the current open source environment in mainland China is not satisfactory. So not fully open source is also a self-protection measure for developers.
