### ISSUE TITLE
Struct error

### ISSUE THREAD

**Issue by project-jj** [fO-000/bluescan#9]
I got an error as below.

<img width="855" alt="스크린샷 2021-01-19 오후 10 50 13" src="https://user-images.githubusercontent.com/77441392/105043648-21ebb380-5aa9-11eb-832b-b71cc889161f.png">

Could you please let me know how to solve this error?

**Comment by fO-000** [comment]
Please provide the following two pieces of information:

* The version of the bluescan you used.
* The command you enter when executing the tool.

**Comment by project-jj** [comment]
The version of the bluescan is 0.4.1.

I have tried to run the command as below.

> sudo bluescan -m br

I got the same error as before.

<img width="902" alt="스크린샷 2021-01-21 오후 10 34 05" src="https://user-images.githubusercontent.com/77441392/105358695-dae0f800-5c39-11eb-90e2-862718022c06.png">

**Comment by fO-000** [comment]
Oh, I see.

All I encountered were `HCI_Extended_Inquiry_Result` events. So even though I wrote the code to parse `HCI_Inquiry_Result` events, it hasn't had a chance to be actually tested.

The correct code should be `<6sBH3sH`, not `<6sBB3sH`. Because the `reserved` parameter in `HCI_Inquiry_Result` events is **2 octets**, instead of **1 octet** in `HCI_Extended_Inquiry_Result` events.

There are two ways to solve this problem:

1. Modify the following code:

   ```py
   # br_scan.py
   def pp_inquiry_result(self, params):
       ... ...
       # struct.unpack('<6sBB3sH', params[1:])
       struct.unpack('<6sBH3sH', params[1:])
       ... ...
       # print('Reserved: 0x%02x'% reserved)
       print('Reserved: 0x%04x' % reserved)
       ... ...
   ```
2. Waiting for the next version of bluescan.

**Comment by project-jj** [comment]
Thank you for your help.
